create table Resumes ( resID int(11) auto_increment primary key, FirstName varchar(25), Middle varchar(25), LastName varchar(25), email varchar(25)); 
select * from Resumes;
create table Education ( EducID int(11) auto_increment primary key, degree varchar(25), field varchar(25),school varchar(25), YearGrad varchar(25), resID int(11)); 
create table Work ( WorkID int(11) auto_increment primary key, WorkTitle varchar(25), WorkComp varchar(25), workDur varchar(25), resID int(11)); 
select * from Work;
select * from Education;
alter table Education modify YearGrad int(11);
select * from Education;
select * from Work;
create table Duties(dutyID int(11) auto_increment primary key, dutyName varchar(25), workID int(11));
create table Skills(skillID int(11) auto_increment primary key, skillName varchar(25), proficiency varchar(25));
select * from Duties;
select * from Skills;
alter table Work add column duty varchar(140);
truncate table Resumes;
truncate table Education;
truncate table Work;
truncate table Skills;
select * from Resumes;
select * from Education;
select * from Work;
select * from Skills;